### ISSUE TITLE
Decide on project topic

### ISSUE THREAD

**Issue by kkorolyov** [kkorolyov/151-Project#1]
### Chosen Ideas

**1 Automatic call rejector (Android)**
**2 "Craiglist" for free stuff**
### Current Ideas

**"Craiglist" for free stuff**
- Web server/site with mobile client application
- Users post unwanted junk, others claim
- Poster rating system?

**Automatic call rejector (Android)**
- Assuming possible/not extremely difficult to wrap around Android phone call API

**Comment by kkorolyov** [comment]
Not sure how good of a topic this is:
**GPS/Location-based Augmented Reality RPG**
- Environment, enemies, loot generated based on geographical location
- \- Rural, residential, high-tech, etc.
- Dungeons generated from landmarks in proximity
- \- Museums, schools, stores, companies, etc.
- Can party with others nearby
- \- Bonus based on party size and proximity

**Comment by baophamtd** [comment]
I have an idea for "Smart Brightness Controller".
As I heard from my friend, he's still looking for an app for Android phones which can automatically adjust the brightness on your phone under some circumstances such as: 
-Low battery
-Night time while you're sleeping (so that it won't hurt your eyes)
What do you guys think about this?

**Comment by baophamtd** [comment]
I also have an idea about an interactive app that helps you to decide what you want to eat.
This app is somewhat like Siri, but it only focuses on food.
First, it can collect all the information about the restaurants close to you. 
Then, it will interact with you by asking questions on what type of food you're in the mood for, or how much time you have for your meals, etc.
Finally, it narrows down to some last options. You choose the restaurant and it will guide you there with Google Maps.

**Comment by iamvictorli** [comment]
The All-around app or software
Instead of multiple applications for different uses, it can be under one application. The User can also choose what can be inside the all-around app
It can consist of:
- an easier user interface for the SETTINGS of the phone, instead of looking throughout the phone 
  e.g brightness, wifi connectivity
- calculator
- notepad
- the everyday use of other applications (could not think of more)
